pnpEnableEsmLoader: true # ESM Support
nodeLinker: pnpm # pnp | pnpm | node-modules

yarnPath: .yarn/releases/yarn-3.2.0.cjs
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
